on:
  workflow_dispatch:
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Print a message
      run: |
        deprecated=true
        if [[deprecated]]; then
          echo "::warning::Deprectade function found"
        fi
