name: First Workflow

on: 
  push:
    branches:
      - main
      
jobs:
  example-job:
    runs-on: ubuntu-lateset

    steps:
      - name: Print a welcome message
        run: echo "welcome to our first GitHub Actions Workflow!"

      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: List repository files
        run: ls -la
